export const url = 'https://evon-api-exam-2.site/wp-json/wp/v2/posts/';
export const homeProducts = 'https://evon-api-exam-2.site/wp-json/wp/v2/posts?categories=10';
export const categoryUrl = 'https://evon-api-exam-2.site/wp-json/wp/v2/posts?categories';
export const urlJWT = 'https://evon-api-exam-2.site/wp-json/jwt-auth/v1/token';
export const baseUrl = 'https://evon-api-exam-2.site/wp-json/';
export const productsUrl = 'https://evon-api-exam-2.site/wp-json/wp/v2/posts?categories=1&per_page=20';
export const messageUrl = 'https://evon-api-exam-2.site/wp-json/wp/v2/posts?categories=11&per_page=100';
export const pdvlProducts = 'https://evon-api-exam-2.site/wp-json/wp/v2/posts?categories=7&per_page=3';
export const enquirFeedback = 'https://evon-api-exam-2.site/wp-json/wp/v2/posts?categories=13&per_page=100';